 <?php
require_once("../Template/Template.php");

$page = new Template("LogOn");
$page->setHeadSection("<link rel='stylesheet' href='../CSS/style.css'>");
$page->setTopSection();
$page->setBottomSection();

print $page->getTopSection();
Print "<header class='nav'>";
print "<div class='location'>";
print "<div class='l3'><form id='frmSearch' class='search2' method='get' action='default.html'>";
print "<input id='txtSearch' type='text' name='serach_bar' size='31' maxlength='255' value='Search' style='width: 225px; height: 10px;'/>";
print "<input type='hidden' name='sitesearch' value='gymHomePage.html'/></form>";
print "</div>";
print "</div>";
Print "<h1>Log In</h1>";
Print "<ul>";
Print "<li><a href='../HomePage/HomePage.php' title='Home Page'>Home Page</a></li>";
Print "<li><a href='../AboutUs/AboutUs.php' title='About Us'>About US</a></li>";
print "<li><a href='../BookSearch/Books.php' title='Book Search'>Book Search</a></li>";
print "<li><a href='../ContactUs/ContactUs.php' title='Contact Us'>Contact Us</a></li>";
Print "</ul>";
Print "</header>";
Print "<body>";
Print "<form class='logon' method='post' action='authentication.php'>";
Print "<fieldset>";
Print "<legend>Log In:</legend>";
Print "<p><label class='b'> User Name: <input type = 'text' id = 'usr' name = 'usr' required></label></p>";
Print "<p><label class='b'> Password: <input type = 'password' name = 'passwd' required></label></p>";
Print "<input type = 'submit' onclick='myFunction()'>";
Print "</fieldset>";
Print "</form>";
Print "</body>";
Print "<footer>";
Print "<p>Book Search</p>";
Print "<p> | </p>";
Print "<p> Privacy Policy </p>";
Print "<p> | </p>";
Print "<p> Terms of Service </p>";
print "<a href = 'https://www.facebook.com/'>";
print "<img src = '../Pictures/facebook.png' alt='facebook'>";
print "</a>";
print "<a href = 'https://twitter.com/?lang=en'>";
print "<img src = '../Pictures/twitter.png' alt='twitter'>";
print "</a>";
print "<a href = 'https://www.instagram.com/?hl=en'>";
print "<img src = '../Pictures/instagram.png' alt='instagram'>";
print "</a>";
Print "</footer>";
print $page->getBottomSection();